package com.springapp.mvc.mappers;

import com.springapp.mvc.entity.mybatis.PageInfo;
import com.springapp.mvc.entity.mybatis.PageInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface PageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oasis_page
     *
     * @mbggenerated Tue Jul 07 16:53:06 CST 2015
     */
    int countByExample(PageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oasis_page
     *
     * @mbggenerated Tue Jul 07 16:53:06 CST 2015
     */
    int deleteByExample(PageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oasis_page
     *
     * @mbggenerated Tue Jul 07 16:53:06 CST 2015
     */
    int deleteByPrimaryKey(Integer pageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oasis_page
     *
     * @mbggenerated Tue Jul 07 16:53:06 CST 2015
     */
    int insert(PageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oasis_page
     *
     * @mbggenerated Tue Jul 07 16:53:06 CST 2015
     */
    int insertSelective(PageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oasis_page
     *
     * @mbggenerated Tue Jul 07 16:53:06 CST 2015
     */
    List<PageInfo> selectByExample(PageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oasis_page
     *
     * @mbggenerated Tue Jul 07 16:53:06 CST 2015
     */
    PageInfo selectByPrimaryKey(Integer pageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oasis_page
     *
     * @mbggenerated Tue Jul 07 16:53:06 CST 2015
     */
    int updateByExampleSelective(@Param("record") PageInfo record, @Param("example") PageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oasis_page
     *
     * @mbggenerated Tue Jul 07 16:53:06 CST 2015
     */
    int updateByExample(@Param("record") PageInfo record, @Param("example") PageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oasis_page
     *
     * @mbggenerated Tue Jul 07 16:53:06 CST 2015
     */
    int updateByPrimaryKeySelective(PageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oasis_page
     *
     * @mbggenerated Tue Jul 07 16:53:06 CST 2015
     */
    int updateByPrimaryKey(PageInfo record);

    @Select("select * from oasis_page order by page_id desc")
    List<PageInfo> selectAllPageIdOrderByDesc ();
}