package com.springapp.mvc.entity.mybatis;

import java.util.Date;

public class IndexInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.id
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.index
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    private String index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.description
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.page_id
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    private Integer pageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.dept_id
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.owner
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.create_time
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.uptime_time
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    private Date uptimeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.id
     *
     * @return the value of oasis_index.id
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.id
     *
     * @param id the value for oasis_index.id
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.index
     *
     * @return the value of oasis_index.index
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public String getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.index
     *
     * @param index the value for oasis_index.index
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public void setIndex(String index) {
        this.index = index == null ? null : index.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.description
     *
     * @return the value of oasis_index.description
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.description
     *
     * @param description the value for oasis_index.description
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.page_id
     *
     * @return the value of oasis_index.page_id
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public Integer getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.page_id
     *
     * @param pageId the value for oasis_index.page_id
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public void setPageId(Integer pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.dept_id
     *
     * @return the value of oasis_index.dept_id
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.dept_id
     *
     * @param deptId the value for oasis_index.dept_id
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.owner
     *
     * @return the value of oasis_index.owner
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.owner
     *
     * @param owner the value for oasis_index.owner
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.create_time
     *
     * @return the value of oasis_index.create_time
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.create_time
     *
     * @param createTime the value for oasis_index.create_time
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.uptime_time
     *
     * @return the value of oasis_index.uptime_time
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public Date getUptimeTime() {
        return uptimeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.uptime_time
     *
     * @param uptimeTime the value for oasis_index.uptime_time
     *
     * @mbggenerated Tue Jul 07 17:52:56 CST 2015
     */
    public void setUptimeTime(Date uptimeTime) {
        this.uptimeTime = uptimeTime;
    }
}