package com.springapp.mvc.entity.mybatis;

import java.util.Date;

public class IndexInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.id
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.index_name
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    private String indexName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.description
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.page_id
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    private Integer pageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.dept_id
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.owner
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.create_time
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.update_time
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.type_id
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_index.is_valid
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.id
     *
     * @return the value of oasis_index.id
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.id
     *
     * @param id the value for oasis_index.id
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.index_name
     *
     * @return the value of oasis_index.index_name
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.index_name
     *
     * @param indexName the value for oasis_index.index_name
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName == null ? null : indexName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.description
     *
     * @return the value of oasis_index.description
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.description
     *
     * @param description the value for oasis_index.description
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.page_id
     *
     * @return the value of oasis_index.page_id
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public Integer getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.page_id
     *
     * @param pageId the value for oasis_index.page_id
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public void setPageId(Integer pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.dept_id
     *
     * @return the value of oasis_index.dept_id
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.dept_id
     *
     * @param deptId the value for oasis_index.dept_id
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.owner
     *
     * @return the value of oasis_index.owner
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.owner
     *
     * @param owner the value for oasis_index.owner
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.create_time
     *
     * @return the value of oasis_index.create_time
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.create_time
     *
     * @param createTime the value for oasis_index.create_time
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.update_time
     *
     * @return the value of oasis_index.update_time
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.update_time
     *
     * @param updateTime the value for oasis_index.update_time
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.type_id
     *
     * @return the value of oasis_index.type_id
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.type_id
     *
     * @param typeId the value for oasis_index.type_id
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_index.is_valid
     *
     * @return the value of oasis_index.is_valid
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_index.is_valid
     *
     * @param isValid the value for oasis_index.is_valid
     *
     * @mbggenerated Thu Aug 06 14:14:00 CST 2015
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}