package com.springapp.mvc.entity.mybatis;

import java.util.Date;

public class PageInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_page.page_id
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    private Integer pageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_page.page_name
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    private String pageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_page.owner
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_page.create_time
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_page.update_time
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_page.description
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_page.type_id
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_page.dept_id
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_page.is_valid
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oasis_page.url_reg
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    private String urlReg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_page.page_id
     *
     * @return the value of oasis_page.page_id
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public Integer getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_page.page_id
     *
     * @param pageId the value for oasis_page.page_id
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public void setPageId(Integer pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_page.page_name
     *
     * @return the value of oasis_page.page_name
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_page.page_name
     *
     * @param pageName the value for oasis_page.page_name
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public void setPageName(String pageName) {
        this.pageName = pageName == null ? null : pageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_page.owner
     *
     * @return the value of oasis_page.owner
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_page.owner
     *
     * @param owner the value for oasis_page.owner
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_page.create_time
     *
     * @return the value of oasis_page.create_time
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_page.create_time
     *
     * @param createTime the value for oasis_page.create_time
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_page.update_time
     *
     * @return the value of oasis_page.update_time
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_page.update_time
     *
     * @param updateTime the value for oasis_page.update_time
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_page.description
     *
     * @return the value of oasis_page.description
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_page.description
     *
     * @param description the value for oasis_page.description
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_page.type_id
     *
     * @return the value of oasis_page.type_id
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_page.type_id
     *
     * @param typeId the value for oasis_page.type_id
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_page.dept_id
     *
     * @return the value of oasis_page.dept_id
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_page.dept_id
     *
     * @param deptId the value for oasis_page.dept_id
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_page.is_valid
     *
     * @return the value of oasis_page.is_valid
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_page.is_valid
     *
     * @param isValid the value for oasis_page.is_valid
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oasis_page.url_reg
     *
     * @return the value of oasis_page.url_reg
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public String getUrlReg() {
        return urlReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oasis_page.url_reg
     *
     * @param urlReg the value for oasis_page.url_reg
     *
     * @mbggenerated Mon Aug 10 10:34:11 CST 2015
     */
    public void setUrlReg(String urlReg) {
        this.urlReg = urlReg == null ? null : urlReg.trim();
    }
}